dist: xenial

language: python
python:
    - "3.7"
install:
    - "pip install -r requirements.txt"

script:
    - export CI_TEST=0
    - "nosetests tests --nologcapture --with-coverage --cover-inclusive --cover-erase --cover-package ."
    - "coverage report -m"
after_success:
    - coveralls
